# Generated by Django 5.1.5 on 2025-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
