# Generated by Django 5.1.5 on 2025-01-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0003_alter_faq_answer_bn_alter_faq_answer_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_hi',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_hi',
        ),
        migrations.AddField(
            model_name='faq',
            name='translations',
            field=models.JSONField(default=dict),
        ),
    ]
