# Generated by Django 5.1.5 on 2025-01-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0004_remove_faq_answer_bn_remove_faq_answer_hi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
